import { TransactionType } from 'src/shared/domain/enums';

export interface SeedCategory {
  name: string;
  type: TransactionType;
  icon: string;
  /** Keywords must be normalized (lowercase, no diacritics) to match parser output. */
  keywords: string[];
}

/**
 * Canonical system categories + keyword mappings. Used by the runtime
 * bootstrap seeder (CategorySeederService).
 */
export const SYSTEM_CATEGORIES: SeedCategory[] = [
  {
    name: 'Makanan',
    type: TransactionType.EXPENSE,
    icon: '🍜',
    keywords: [
      'makan',
      'makanan',
      'kopi',
      'ngopi',
      'bakso',
      'mie ayam',
      'mie',
      'nasi',
      'nasi goreng',
      'ayam',
      'soto',
      'sate',
      'gorengan',
      'jajan',
      'snack',
      'cemilan',
      'gofood',
      'grabfood',
      'martabak',
      'roti',
      'kue',
      'sarapan',
      'makan siang',
      'makan malam',
    ],
  },
  {
    name: 'Minuman',
    type: TransactionType.EXPENSE,
    icon: '🥤',
    keywords: ['minum', 'minuman', 'teh', 'jus', 'boba', 'es teh', 'kopi susu', 'air mineral'],
  },
  {
    name: 'Transportasi',
    type: TransactionType.EXPENSE,
    icon: '🛵',
    keywords: [
      'bensin',
      'isi bensin',
      'pertalite',
      'pertamax',
      'solar',
      'dexlite',
      'grab',
      'gojek',
      'gocar',
      'grabbike',
      'ojek',
      'ojol',
      'taksi',
      'taxi',
      'parkir',
      'tol',
      'busway',
      'transjakarta',
      'krl',
      'kereta',
      'angkot',
      'bus',
      'travel',
    ],
  },
  {
    name: 'Belanja',
    type: TransactionType.EXPENSE,
    icon: '🛍️',
    keywords: [
      'belanja',
      'baju',
      'celana',
      'sepatu',
      'sandal',
      'tas',
      'kosmetik',
      'skincare',
      'shopee',
      'tokopedia',
      'lazada',
      'tiktok shop',
      'groceries',
      'supermarket',
      'indomaret',
      'alfamart',
    ],
  },
  {
    name: 'Tagihan',
    type: TransactionType.EXPENSE,
    icon: '🧾',
    keywords: [
      'listrik',
      'token listrik',
      'pln',
      'air',
      'pdam',
      'internet',
      'wifi',
      'pulsa',
      'paket data',
      'kuota',
      'bpjs',
      'iuran',
      'sewa',
      'kontrakan',
      'kos',
      'kost',
      'cicilan',
      'tagihan',
    ],
  },
  {
    name: 'Hiburan',
    type: TransactionType.EXPENSE,
    icon: '🎮',
    keywords: [
      'nonton',
      'bioskop',
      'film',
      'game',
      'top up',
      'topup',
      'netflix',
      'spotify',
      'youtube',
      'langganan',
      'wisata',
      'liburan',
      'tiket',
      'konser',
      'karaoke',
    ],
  },
  {
    name: 'Kesehatan',
    type: TransactionType.EXPENSE,
    icon: '💊',
    keywords: [
      'obat',
      'apotek',
      'apotik',
      'dokter',
      'rumah sakit',
      'rs',
      'klinik',
      'vitamin',
      'periksa',
      'medical',
      'gym',
      'fitness',
    ],
  },
  {
    name: 'Pendidikan',
    type: TransactionType.EXPENSE,
    icon: '📚',
    keywords: ['buku', 'kursus', 'les', 'spp', 'kuliah', 'sekolah', 'seminar', 'pelatihan'],
  },
  {
    name: 'Lainnya',
    type: TransactionType.EXPENSE,
    icon: '📦',
    keywords: ['lainnya', 'lain', 'misc'],
  },
  {
    name: 'Gaji',
    type: TransactionType.INCOME,
    icon: '💼',
    keywords: ['gaji', 'salary', 'gajian', 'upah', 'payroll'],
  },
  {
    name: 'Bonus',
    type: TransactionType.INCOME,
    icon: '🎁',
    keywords: ['bonus', 'thr', 'insentif', 'komisi', 'reward'],
  },
  {
    name: 'Usaha',
    type: TransactionType.INCOME,
    icon: '🏪',
    keywords: ['jualan', 'usaha', 'dagang', 'omzet', 'penjualan', 'profit', 'untung'],
  },
  {
    name: 'Pemasukan Lain',
    type: TransactionType.INCOME,
    icon: '💰',
    keywords: ['dapat uang', 'transfer masuk', 'hadiah', 'dividen', 'bunga', 'refund', 'cashback'],
  },
];
